// Festival Sokoban Solver
// Copyright 2018-2022 Yaron Shoham

#include <stdio.h>
#include <stdlib.h>

#include "global.h"
#include "util.h"

char solver_name[100] = "Festival 3.1";

int time_limit = 600;

int height;
int width;

int verbose = 3;

int delta_y[4] = { -1, 0, 1, 0 };
int delta_x[4] = { 0, 1, 0, -1 };

int delta_y_8[8] = { -1, -1, 0, 1, 1, 1, 0, -1 };
int delta_x_8[8] = { 0, 1, 1, 1, 0, -1, -1, -1 };


int level_id = 0;
char level_title[1000];

int global_initial_sokoban_y, global_initial_sokoban_x;
int global_boxes_in_level;

int cores_num = -1;

int any_core_solved;

#ifdef VISUAL_STUDIO
char global_dir[1000] = "c:\\sokoban";
#else
char global_dir[1000] = ".";
#endif

char global_output_filename[1000] = "";
int YASC_mode = 0;
int save_best_flag = 0;
int extra_mem = 0;

char global_fail_reason[50];

int start_time, end_time;

int just_one_level    = -1;
int global_from_level = -1;
int global_to_level   = -1;

char global_level_set_name[1000] = "XSokoban";
//char global_level_set_name[1000] = "Microban";
//char global_level_set_name[1000] = "Microban II";
//char global_level_set_name[1000] = "Yoshio Murase handmade";
//char global_level_set_name[1000] = "Yoshio Murase autogenerated";
//char global_level_set_name[1000] = "Aymeric";
//char global_level_set_name[1000] = "SokEvo";
//char global_level_set_name[1000] = "Sasquatch I"; 
//char global_level_set_name[1000] = "Sasquatch II";
//char global_level_set_name[1000] = "Sasquatch III";
//char global_level_set_name[1000] = "Sasquatch IV";
//char global_level_set_name[1000] = "Sasquatch V";
//char global_level_set_name[1000] = "Sasquatch VI";
//char global_level_set_name[1000] = "Sasquatch VII";
//char global_level_set_name[1000] = "SokHard";
//char global_level_set_name[1000] = "Grigr2001";
//char global_level_set_name[1000] = "Grigr2002";
//char global_level_set_name[1000] = "GrigrSpecial";
//char global_level_set_name[1000] = "small_test";
//char global_level_set_name[1000] = "sven_1911";
//char global_level_set_name[1000] = "Holland";
//char global_level_set_name[1000] = "Perfect";
//char global_level_set_name[1000] = "Kevin_1";
//char global_level_set_name[1000] = "disciple";
//char global_level_set_name[1000] = "numbers";
//char global_level_set_name[1000] = "greek";
//char global_level_set_name[1000] = "kobus_Theron";
//char global_level_set_name[1000] = "Perfect";
//char global_level_set_name[1000] = "revenge";
//char global_level_set_name[1000] = "Serg_Belyaev_4";
//char global_level_set_name[1000] = "sharpen";
//char global_level_set_name[1000] = "sven_easy";
//char global_level_set_name[1000] = "bugs5";
//char global_level_set_name[1000] = "all_sas";
//char global_level_set_name[1000] = "medium";